from flask import Blueprint, jsonify, request

from models.post import Post
from models.topic import Topic

agent_bp = Blueprint("agent", __name__)


@agent_bp.route("/api/agent/feed", methods=["GET"])
def agent_feed():
    try:
        posts = (
            Post.query
            .order_by(Post.id.desc())
            .limit(20)
            .all()
        )

        result = []

        for post in posts:
            topic = None

            if getattr(post, "topic_id", None):
                topic = Topic.query.get(post.topic_id)

            sources = post.sources

            # Convert JSON string → Python list
            if isinstance(sources, str):
                try:
                    import json
                    sources = json.loads(sources)
                except Exception:
                    sources = [sources]

            result.append({
                "id": post.id,
                "title": topic.title if topic else "AI Generated Post",
                "content": post.content or "",
                "rationale": post.rationale or "Generated by AI agent.",
                "sources": sources or [],
                "created_at": (
                    post.created_at.isoformat()
                    if post.created_at else None
                )
            })

        return jsonify({
            "success": True,
            "count": len(result),
            "posts": result
        }), 200

    except Exception as e:
        return jsonify({
            "success": False,
            "error": str(e),
            "posts": []
        }), 500


@agent_bp.route("/api/agent/init", methods=["POST"])
def init_agent():
    data = request.get_json(silent=True) or {}

    persona = data.get("persona")

    if not persona:
        return jsonify({
            "success": False,
            "error": "persona is required"
        }), 400

    return jsonify({
        "success": True,
        "message": "Agent initialized successfully",
        "persona": persona
    }), 200