from flask import Blueprint, jsonify, request
import json
import uuid

from database.db import db
from models.post import Post
from models.topic import Topic

agent_bp = Blueprint("agent", __name__)


@agent_bp.route("/api/agent/feed", methods=["GET"])
def agent_feed():
    try:
        posts = (
            Post.query
            .order_by(Post.id.desc())
            .limit(20)
            .all()
        )

        result = []

        for post in posts:
            topic = Topic.query.get(post.topic_id)

            sources = post.sources

            if isinstance(sources, str):
                try:
                    sources = json.loads(sources)
                except Exception:
                    sources = [sources]

            result.append({
                "id": post.id,
                "title": topic.title if topic else "AI Generated Post",
                "content": post.content or "",
                "rationale": post.rationale or "Generated by AI agent.",
                "sources": sources or [],
                "status": post.status,
                "created_at": (
                    post.created_at.isoformat()
                    if post.created_at else None
                )
            })

        return jsonify({
            "success": True,
            "count": len(result),
            "posts": result
        }), 200

    except Exception as e:
        return jsonify({
            "success": False,
            "error": f"{type(e).__name__}: {str(e)}",
            "posts": []
        }), 500


@agent_bp.route("/api/agent/init", methods=["POST"])
def init_agent():
    try:
        data = request.get_json(silent=True)

        if not isinstance(data, dict):
            return jsonify({
                "success": False,
                "error": "Request body must be valid JSON"
            }), 400

        persona = data.get("persona")

        if not isinstance(persona, dict):
            return jsonify({
                "success": False,
                "error": "persona must be an object"
            }), 400

        name = str(persona.get("name") or "AI Agent").strip()
        domain = str(
            persona.get("domain") or "Artificial Intelligence"
        ).strip()

        topic = Topic(
            title=f"{name} - {domain}",
            source="Autonomous AI Creator",
            url=f"https://autonomous-ai-creator.local/topic/{uuid.uuid4()}",
            score=1.0,
            status="scored",
            reason="Created during agent initialization."
        )

        db.session.add(topic)
        db.session.flush()

        post = Post(
            topic_id=topic.id,
            content=(
                f"Hello! I am {name}, an autonomous AI creator "
                f"focused on {domain}. "
                f"This is my first AI-generated post."
            ),
            rationale="Initial post generated during agent initialization.",
            sources=json.dumps([]),
            status="published"
        )

        db.session.add(post)
        db.session.commit()

        return jsonify({
            "success": True,
            "message": "Agent initialized successfully",
            "persona": {
                "name": name,
                "domain": domain
            },
            "topic_id": topic.id,
            "post_id": post.id
        }), 200

    except Exception as e:
        db.session.rollback()

        print(f"[AGENT INIT ERROR] {type(e).__name__}: {e}")

        return jsonify({
            "success": False,
            "error": f"{type(e).__name__}: {str(e)}"
        }), 500
@agent_bp.route("/api/agent/topic", methods=["POST"])
def create_topic():
    try:
        data = request.get_json(silent=True) or {}

        title = str(
            data.get("title") or
            "The Future of Autonomous AI Agents"
        ).strip()

        source = str(
            data.get("source") or
            "Autonomous AI Creator"
        ).strip()

        url = f"https://autonomous-ai-creator.local/topic/{uuid.uuid4()}"

        topic = Topic(
            title=title,
            source=source,
            url=url,
            score=1.0,
            status="scored",
            reason="Topic generated by the autonomous topic discovery system."
        )

        db.session.add(topic)
        db.session.commit()

        return jsonify({
            "success": True,
            "message": "Topic created successfully",
            "topic": {
                "id": topic.id,
                "title": topic.title,
                "source": topic.source,
                "url": topic.url,
                "score": topic.score,
                "status": topic.status,
                "reason": topic.reason,
                "created_at": (
                    topic.created_at.isoformat()
                    if topic.created_at else None
                )
            }
        }), 201

    except Exception as e:
        db.session.rollback()

        print(f"[TOPIC ERROR] {type(e).__name__}: {e}")

        return jsonify({
            "success": False,
            "error": f"{type(e).__name__}: {str(e)}"
        }), 500
 
@agent_bp.route("/api/agent/generate", methods=["POST"])
def generate_post():
    try:
        data = request.get_json(silent=True) or {}

        topic_id = data.get("topic_id")

        if topic_id:
            topic = Topic.query.get(int(topic_id))
        else:
            topic = (
                Topic.query
                .order_by(Topic.id.desc())
                .first()
            )

        if not topic:
            return jsonify({
                "success": False,
                "error": "No topic available"
            }), 404

        title = topic.title

        content = (
            f"{title} is becoming an important area in modern "
            f"artificial intelligence. Autonomous AI systems can "
            f"identify relevant topics, analyze information, and "
            f"turn those insights into useful content with minimal "
            f"human intervention. "
            f"\n\n"
            f"The key advantage is the ability to continuously "
            f"discover topics, evaluate their relevance, and "
            f"produce structured content automatically. This can "
            f"help creators and organizations stay informed while "
            f"reducing repetitive manual work."
        )

        rationale = (
            "Post generated autonomously from the selected topic. "
            "The agent converted the topic into structured "
            "AI-focused content."
        )

        post = Post(
            topic_id=topic.id,
            content=content,
            rationale=rationale,
            sources=json.dumps([topic.url]),
            status="published"
        )

        db.session.add(post)
        db.session.commit()

        return jsonify({
            "success": True,
            "message": "Post generated successfully",
            "post": {
                "id": post.id,
                "topic_id": topic.id,
                "title": topic.title,
                "content": post.content,
                "rationale": post.rationale,
                "sources": [topic.url],
                "status": post.status,
                "created_at": (
                    post.created_at.isoformat()
                    if post.created_at else None
                )
            }
        }), 201

    except Exception as e:
        db.session.rollback()

        print(f"[GENERATE ERROR] {type(e).__name__}: {e}")

        return jsonify({
            "success": False,
            "error": f"{type(e).__name__}: {str(e)}"
        }), 500
