from flask import Blueprint, jsonify, request
import json
import uuid

from database.db import db
from models.post import Post
from models.topic import Topic


agent_bp = Blueprint("agent", __name__)


@agent_bp.route("/api/agent/feed", methods=["GET"])
def agent_feed():
    try:
        posts = (
            Post.query
            .order_by(Post.id.desc())
            .limit(20)
            .all()
        )

        result = []

        for post in posts:
            topic = None

            if getattr(post, "topic_id", None):
                topic = Topic.query.get(post.topic_id)

            sources = post.sources

            if isinstance(sources, str):
                try:
                    sources = json.loads(sources)
                except Exception:
                    sources = [sources]

            result.append({
                "id": post.id,
                "title": topic.title if topic else "AI Generated Post",
                "content": post.content or "",
                "rationale": post.rationale or "Generated by AI agent.",
                "sources": sources or [],
                "created_at": (
                    post.created_at.isoformat()
                    if post.created_at else None
                )
            })

        return jsonify({
            "success": True,
            "count": len(result),
            "posts": result
        }), 200

    except Exception as e:
        return jsonify({
            "success": False,
            "error": str(e),
            "posts": []
        }), 500


@agent_bp.route("/api/agent/init", methods=["POST"])
def init_agent():
    try:
        data = request.get_json(silent=True) or {}
        persona = data.get("persona")

        if not persona:
            return jsonify({
                "success": False,
                "error": "persona is required"
            }), 400

        name = persona.get("name", "AI Agent")
        domain = persona.get("domain", "Artificial Intelligence")

        # Create a topic.
        # Topic requires title, source and unique URL.
        topic = Topic(
            title=f"{name} - {domain}",
            source="Autonomous AI Creator",
            url=f"https://autonomous-ai-creator.local/topic/{uuid.uuid4()}",
            reason="Topic created during autonomous agent initialization."
        )

        db.session.add(topic)
        db.session.flush()

        # Create the first AI-generated post.
        # Post.sources is a TEXT column, so store JSON text.
        post = Post(
            topic_id=topic.id,
            content=(
                f"Hello! I am {name}, an autonomous AI creator "
                f"focused on {domain}. "
                f"This is my first AI-generated post."
            ),
            rationale="Initial post generated when the AI agent was initialized.",
            sources=json.dumps([])
        )

        db.session.add(post)
        db.session.commit()

        return jsonify({
            "success": True,
            "message": "Agent initialized successfully",
            "persona": persona,
            "post_id": post.id
        }), 200

    except Exception as e:
        db.session.rollback()

        return jsonify({
            "success": False,
            "error": str(e)
        }), 500